const data = {
    products: [
        {name: "Tenere 700",
        slug:  " tenere 700",
        category: "ADV Bikes",
        image: "/images/tenere1.jpg",
        price: 8000,
        countInStock: 3,
        brand: "Yamaha",
        rating: 4.6,
        numReviews: 10,
        description: "great ADV",
        },

        {name: "African Twin 1200",
        slug:  " African Twin",
        category: "ADV Bikes",
        image: "/images/african1.jpg",
        price: 10000,
        countInStock: 3,
        brand: "Honda",
        rating: 4.5,
        numReviews: 7,
        description: "great ADV",
        },

        {name: "BMW GS 1200",
        slug:  " bmw gs ",
        category: "ADV Bikes",
        image: "/images/bmw1.jpg",
        price: 8000,
        countInStock: 3,
        brand: "BMW",
        rating: 4.6,
        numReviews: 15,
        description: "great ADV",
        },


        {name: "KLX 650",
        slug:  " klx ",
        category: "ADV Bikes",
        image: "/images/kawa1.jpg",
        price: 8000,
        countInStock: 3,
        brand: "Kawasaki",
        rating: 4.4,
        numReviews: 9,
        description: "great ADV",
        },

        {name: "Multistada 950",
        slug:  " multistrada ",
        category: "ADV Bikes",
        image: "/images/ducatti1.jpg",
        price: 16000,
        countInStock: 1,
        brand: "Ducatti",
        rating: 4.6,
        numReviews: 3,
        description: "great ADV",
        },

        {name: "Tiger 660",
        slug:  " Tiger ",
        category: "ADV Bikes",
        image: "/images/tiger1.jpg",
        price: 13000,
        countInStock: 3,
        brand: "Triumph",
        rating: 4.5,
        numReviews: 3,
        description: "great ADV",
        },
    ]
}

export default data;